language: node_js
node_js:
  - "node"
script: npm test && npm run build
deploy:
  local-dir: build
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
  verbose: true
